### ISSUE TITLE
Theme text is broken

### ISSUE THREAD

**Issue by Chosen-Marsh** [JWalkerMailly/Gmod-Github-Theme#1]
The theme works fine its just the text for example where it should say "Start new game" it says "new_game"

![image](https://github.com/JWalkerMailly/Gmod-Github-Theme/assets/90572327/c54e8f5f-32b4-4d08-a4f9-13aabcfc1405)

The Q menu is also like this but a bit more broken

![image](https://github.com/JWalkerMailly/Gmod-Github-Theme/assets/90572327/9c9f4821-7681-4b23-89e0-258c9aae6303)

**Comment by JWalkerMailly** [comment]
Hi Marsh, how was the theme installed? Looks like some files were not replaced correctly. It also shouldn't mess with the Q menu. On what branch are you currently?

**Comment by JWalkerMailly** [comment]
My guess at the moment would be when you backed up the folders mentioned, you actually removed them completely in favor of the ones from this repo. Try reverting back and then dropping the folders from this repo on top of the others and overwrite files with the same name instead. Let me know if this helps.

**Comment by Chosen-Marsh** [comment]
Never You was right I was an idiot
